require("alex.packages")
require("alex.opts")
require("alex.treesitter")
require("alex.mason-lsp")
require("alex.nvim-dap")
require("alex.rust-tools")
require("alex.telescope")
require("alex.nvim-dap-virtual-text")
-- require("alex.nvim-dap-ui")
require("alex.zenburn")
require("alex.nvim-comment")
require("alex.null-ls")
require("alex.tree")
require("alex.keybindings")
require("alex.fterm")
require("alex.bufferline")
require("alex.alpha")
