require("alex.packages")
require("alex.lsp")
require("alex.null-ls")
-- Above changes while reinstalling the lsp and autoformat
require("alex.keybindings")
require("alex.config")
require("alex.truezen")
require("alex.comment")
require("alex.lualine")
require("alex.tree")
require("alex.telescope")
require("alex.treesitter")
require("alex.nvim-nonicons")
require("alex.bufferline")
require("alex.gitsigns")
require("alex.todo-comments")
require("alex.fterm")
require('alex.project')
